version: '3.3'
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/home/user/api
    environment:
      - POSTGRES_HOST=db
    ports:
      - 8000:8000
    depends_on:
      - migration
      - db
  migration:
    build: .
    command: python manage.py migrate
    volumes:
      - ./api:/home/user/api
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80