# Generated by Django 3.2.8 on 2021-10-26 11:42

import core.custom_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genome', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', core.custom_fields.CommaSepField(null=True)),
                ('outputs', core.custom_fields.CommaSepField(null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.environment')),
            ],
        ),
    ]
