# Generated by Django 3.2.8 on 2021-10-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='fitness',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
