# Generated by Django 3.2.8 on 2021-10-26 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_agent_fitness'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='environment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logic.environment'),
            preserve_default=False,
        ),
    ]
