# Generated by Django 3.2.8 on 2021-10-26 10:19

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_auto_20211026_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('ouputs', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.environment')),
            ],
        ),
    ]
