# Generated by Django 3.2.8 on 2021-10-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_agent_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='genome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
